apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoutifii-app
spec:
  replicas: 3   # more than one deployments by default its 1
  selector:
    matchLabels:
      app: scoutifii-app
  template:
    metadata:
      labels:
        app: scoutifii-app
    spec:
      containers:
        - name: nginx
          image: nginx-latest   # image coming directly from docker hub
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            


