from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('signup', views.signup, name='signup'), 
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('settings', views.settings, name='settings'),
    path('like-post', views.like_post, name='like-post'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('follower/<str:pk>', views.follower, name='follower'),
    path('following/<str:pk>', views.following, name='following'),
    path('follow', views.follow, name='follow'),
    path('user-post/<str:id>', views.user_post, name='user-post'),
    path('report', views.report, name='report'),
    path('notifications', views.show_notifications, name='notifications'),
    path('search', views.search, name='search'),
    path('flair/<uuid:id>', views.flair, name='flair'),
    path('positioning/<str:pk>', views.positioning, name='positioning'),
    path('marking/<str:pk>', views.marking, name='marking'),
    path('anticipation/<str:pk>', views.anticipation, name='anticipation'),
    path('offtheball/<str:pk>', views.offtheball, name='offtheball'),
    path('tackling/<str:pk>', views.tackling, name='tackling'),
    path('vision/<str:pk>', views.vision, name='vision'),
    path('speed/<str:pk>', views.speed, name='speed'),
    path('heading/<str:pk>', views.heading, name='heading'),
    path('jumpingreach/<str:pk>', views.jumping_reach, name='jumpingreach'),
    path('workrate/<str:pk>', views.work_rate, name='workrate'),
    path('aggression/<str:pk>', views.aggression, name='aggression'),
    path('charisma/<str:pk>', views.charisma, name='charisma'),
    path('ballprotection/<str:pk>', views.ball_protection, name='ballprotection'),
    path('shooting/<str:pk>', views.shooting, name='shooting'),
    path('technique/<str:pk>', views.technique, name='technique'),
    path('passing/<str:pk>', views.passing, name='passing'),
    path('finishing/<str:pk>', views.finishing, name='finishing'),
    path('ballcontrol/<str:pk>', views.ball_control, name='ballcontrol'),
    path('freekick/<str:pk>', views.free_kick, name='freekick'),
    path('dribbling/<str:pk>', views.dribbling, name='dribbling'),
    path('crossing/<str:pk>', views.crossing, name='crossing'),
    path('pace/<str:pk>', views.pace, name='pace'),
    path('user-comments/<str:id>', views.user_comments, name='user-comments'),
    path('autosuggest', views.autosuggest, name='autosuggest'),
]