# Generated by Django 5.2.6 on 2025-09-10 09:20

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import scoutifiiapp.helper
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('brand_logo', models.ImageField(upload_to='brand_images', validators=[scoutifiiapp.helper.validate_image_file_extension, scoutifiiapp.helper.validate_image_file_size])),
                ('favicon_icon', models.ImageField(upload_to='brand_images', validators=[scoutifiiapp.helper.validate_image_file_extension, scoutifiiapp.helper.validate_image_file_size])),
                ('brand_footer', models.CharField(max_length=1000)),
                ('brand_slogan', models.CharField(max_length=50, null=True)),
                ('about', models.TextField()),
                ('google_analytics', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brand_setting',
            },
        ),
        migrations.CreateModel(
            name='AllLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('last_logged_out', models.DateTimeField()),
                ('ip_address', models.CharField(blank=True, default=0, max_length=100)),
                ('server', models.CharField(blank=True, default=0, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'all_logins',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(blank=True, default='default-user.png', upload_to='profile_images', validators=[scoutifiiapp.helper.validate_image_file_extension, scoutifiiapp.helper.validate_image_file_size])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, unique=True)),
                ('forgot_password_token', models.CharField(max_length=100)),
                ('country_id', django_countries.fields.CountryField(max_length=2)),
                ('profile_type_data', models.CharField(default='user', max_length=10)),
                ('birth_date', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('user_prof', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(max_length=255, upload_to='player_videos/%Y/%m/%d', validators=[scoutifiiapp.helper.validate_video_file_extension, scoutifiiapp.helper.validate_video_file_size])),
                ('video_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category_type', models.CharField(choices=[('football', 'Football'), ('netball', 'Netball'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('athletics', 'Athletics'), ('boxing', 'Boxing')], max_length=50, null=True)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('no_of_views', models.IntegerField(default=0)),
                ('no_of_flair', models.IntegerField(default=0)),
                ('no_of_off_the_ball', models.IntegerField(default=0)),
                ('no_of_positioning', models.IntegerField(default=0)),
                ('no_of_marking', models.IntegerField(default=0)),
                ('no_of_anticipation', models.IntegerField(default=0)),
                ('no_of_pace', models.IntegerField(default=0)),
                ('no_of_tackling', models.IntegerField(default=0)),
                ('no_of_vision', models.IntegerField(default=0)),
                ('no_of_work_rate', models.IntegerField(default=0)),
                ('no_of_aggression', models.IntegerField(default=0)),
                ('no_of_charisma', models.IntegerField(default=0)),
                ('no_of_ball_protection', models.IntegerField(default=0)),
                ('no_of_speed', models.IntegerField(default=0)),
                ('no_of_heading', models.IntegerField(default=0)),
                ('no_of_jumping_reach', models.IntegerField(default=0)),
                ('no_of_shooting', models.IntegerField(default=0)),
                ('no_of_technique', models.IntegerField(default=0)),
                ('no_of_passing', models.IntegerField(default=0)),
                ('no_of_finishing', models.IntegerField(default=0)),
                ('no_of_ball_control', models.IntegerField(default=0)),
                ('no_of_free_kick', models.IntegerField(default=0)),
                ('no_of_dribbling', models.IntegerField(default=0)),
                ('no_of_crossing', models.IntegerField(default=0)),
                ('no_of_concentration', models.IntegerField(default=0)),
                ('no_of_agility', models.IntegerField(default=0)),
                ('no_of_reflexes', models.IntegerField(default=0)),
                ('no_of_saving_penalties', models.IntegerField(default=0)),
                ('no_of_footwork_and_distribution', models.IntegerField(default=0)),
                ('no_of_commanding_in_defence', models.IntegerField(default=0)),
                ('no_of_saving_one_on_one', models.IntegerField(default=0)),
                ('no_of_handling', models.IntegerField(default=0)),
                ('no_of_aerial_ability', models.IntegerField(default=0)),
                ('no_of_close_range_shot_stopping_ability', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scoutifiiapp.profile')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
