# Generated by Django 5.2.6 on 2025-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0003_alter_brandsetting_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllogins',
            name='last_logged_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
