# Generated by Django 5.2.6 on 2025-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0004_alter_alllogins_last_logged_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllogins',
            name='browser',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='alllogins',
            name='device_type',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='alllogins',
            name='user_agent',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
