# Generated by Django 5.2.6 on 2025-09-23 15:47

import scoutifiiapp.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0005_alllogins_browser_alllogins_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, storage=scoutifiiapp.helper.VideoStorage, upload_to='', validators=[scoutifiiapp.helper.validate_video_file_extension, scoutifiiapp.helper.validate_video_file_size, scoutifiiapp.helper.validate_video_mime]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='default-user.png', upload_to='profile_images', validators=[scoutifiiapp.helper.validate_image_file_extension, scoutifiiapp.helper.validate_image_file_size, scoutifiiapp.helper.validate_image_mime]),
        ),
        migrations.AddConstraint(
            model_name='followerscount',
            constraint=models.UniqueConstraint(fields=('follower', 'user'), name='unique_follow_pair'),
        ),
    ]
