# Generated by Django 5.2.6 on 2025-09-24 07:14

import scoutifiiapp.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0006_alter_post_video_alter_profile_profileimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, storage=scoutifiiapp.helper.VideoStorage, upload_to='%Y/%m/%d', validators=[scoutifiiapp.helper.validate_video_file_extension, scoutifiiapp.helper.validate_video_file_size, scoutifiiapp.helper.validate_video_mime]),
        ),
    ]
