# Generated by Django 5.2.6 on 2025-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0011_overageevent_created_at_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_count',
            field=models.IntegerField(default=0),
        ),
    ]
