# Generated by Django 5.2.6 on 2025-09-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0012_post_repost_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='scoutifiiapp.profile'),
        ),
    ]
