# Generated by Django 5.2.6 on 2025-10-04 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0015_adplacement_advertiser_adimpression_adclick_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videocounts',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='videocounts',
            index=models.Index(fields=['post', 'user'], name='video_count_post_id_e8265e_idx'),
        ),
        migrations.AddIndex(
            model_name='videocounts',
            index=models.Index(fields=['post', 'session'], name='video_count_post_id_a58566_idx'),
        ),
        migrations.AddIndex(
            model_name='videocounts',
            index=models.Index(fields=['post', 'ip_address'], name='video_count_post_id_dd7581_idx'),
        ),
    ]
