# Generated by Django 5.2.6 on 2025-10-15 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0017_livestream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completeness_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='dominant_side',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='secondary_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(default='unverified', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup_status', models.CharField(blank=True, max_length=10)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('event_counts', models.JSONField(default=dict)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('clip_ids', models.JSONField(blank=True, default=list)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='scoutifiiapp.profile')),
            ],
            options={
                'db_table': 'match_log',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='scoutifiiapp.profile')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('summary', models.TextField(max_length=2000)),
                ('traits', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('roles_suited', models.JSONField(default=list)),
                ('grade', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_reports', to='scoutifiiapp.profile')),
            ],
            options={
                'db_table': 'scouting_report',
            },
        ),
        migrations.CreateModel(
            name='SeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=12)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('appearances', models.PositiveSmallIntegerField(default=0)),
                ('role_metrics', models.JSONField(default=dict)),
                ('per90', models.JSONField(default=dict)),
                ('sources', models.JSONField(default=list)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='scoutifiiapp.profile')),
            ],
            options={
                'db_table': 'season_stat',
                'unique_together': {('player', 'season_id')},
            },
        ),
    ]
