# Generated by Django 5.2.6 on 2025-10-28 07:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0018_profile_completeness_score_profile_dominant_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=13, null=True, region=None),
        ),
    ]
