# Generated by Django 5.2.6 on 2025-10-30 10:32

import scoutifiiapp.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0019_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/%d', verbose_name=scoutifiiapp.helper.VideoStorage),
        ),
        migrations.AddField(
            model_name='livestream',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
