# Generated by Django 5.2.6 on 2025-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutifiiapp', '0021_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.CharField(default='bg-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font_size',
            field=models.CharField(default='13px', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='color-1', max_length=20),
        ),
    ]
